In [1]:
import numpy as np

In [5]:
x = []
for i in range(0, 1000, 100):
    x.append(np.random.randn(0,1))
x

[array([ 0.23969971, -1.62298693, -1.34147426, -0.17831604, -1.06854523,
         1.75792092, -1.03473126, -0.75309877, -0.08508525,  0.7089899 ]),
 array([ 1.11054554, -1.06196382, -0.68481263,  0.33568193, -1.8658846 ,
         0.44116643, -0.58531696, -1.10693728, -1.04782453, -0.15446181]),
 array([ 0.21629375, -0.07112896,  0.63916257, -0.58957455,  0.13293744,
         0.23739719,  1.44549291, -1.65599647, -0.14631544, -0.86882865]),
 array([-1.14978494,  1.49708988,  0.65967588,  1.04160911, -0.31273904,
         1.17508155,  0.16727118,  1.31730832,  0.13980406, -0.10715131]),
 array([ 1.14683739, -0.97899269,  0.46517218,  1.04685971, -0.59302882,
        -0.56354755, -0.17713156,  0.31607051,  0.70622179,  0.60859697]),
 array([ 0.79649256, -2.18708846, -2.10849664,  0.75206259,  1.89845643,
         0.62101773,  0.06498175,  1.4931699 , -1.95591035,  1.07910628]),
 array([-0.0137632 ,  0.65232787,  1.01834502, -0.52029276, -0.12587201,
         0.17781231,  0.64727967,  0.74

In [37]:
random_num = []
for i in np.random.rand(10):
    random_num.append(round(i))
random_num

[0, 0, 0, 0, 1, 1, 1, 1, 0, 0]

In [38]:
count = 0
for i in random_num:
    if i == 1:
        count += 1
print(count, count/10)
np.mean(random_num)

4 0.4


In [40]:
np.std(random_num)

0.48989794855663565

In [28]:
random_num = []
for i in np.random.rand(100):
    random_num.append(round(i))

In [29]:
count = 0
for i in random_num:
    if i == 1:
        count += 1
print(count, count/100)

58 0.58


In [30]:
random_num = []
for i in np.random.rand(1000):
    random_num.append(round(i))


In [31]:
count = 0
for i in random_num:
    if i == 1:
        count += 1
print(count, count/1000)

491 0.491


In [25]:
random_num = []
for i in np.random.rand(100000):
    random_num.append(round(i))
count = 0
for i in random_num:
    if i == 1:
        count += 1
print(count, count/100000)

50130 0.5013


As sample size increases; accuracy increases

In [32]:
random_num = []
for i in np.random.rand(10000000):
    random_num.append(round(i))
count = 0
for i in random_num:
    if i == 1:
        count += 1
print(count, count/10000000)

5000391 0.5000391


### Populations vs Sample

In [45]:
population = np.random.randint(10,20,1000) # start,stop,no_of_numbers

In [46]:
population

array([11, 13, 15, 16, 15, 14, 18, 18, 15, 17, 10, 14, 16, 17, 14, 17, 10,
       15, 13, 19, 11, 12, 11, 12, 12, 14, 10, 18, 14, 10, 17, 10, 14, 11,
       18, 11, 16, 13, 14, 16, 11, 19, 17, 14, 17, 19, 14, 19, 19, 11, 17,
       10, 18, 10, 11, 13, 18, 15, 13, 12, 16, 16, 15, 19, 18, 11, 14, 19,
       16, 18, 11, 17, 14, 15, 14, 17, 14, 13, 14, 19, 15, 13, 14, 12, 16,
       10, 14, 16, 13, 15, 19, 19, 12, 16, 14, 11, 13, 13, 15, 15, 17, 12,
       16, 12, 18, 13, 13, 15, 18, 16, 10, 18, 17, 14, 19, 15, 12, 19, 17,
       19, 15, 19, 18, 14, 10, 18, 15, 12, 11, 19, 13, 16, 18, 13, 15, 19,
       14, 16, 19, 15, 11, 15, 13, 19, 17, 15, 12, 19, 17, 16, 19, 10, 19,
       10, 15, 13, 17, 19, 10, 10, 17, 17, 19, 10, 17, 17, 17, 18, 14, 11,
       10, 16, 19, 18, 14, 10, 18, 17, 11, 17, 12, 10, 16, 11, 15, 17, 18,
       14, 11, 17, 16, 18, 16, 17, 15, 15, 13, 13, 16, 18, 17, 19, 14, 19,
       18, 10, 18, 18, 10, 11, 17, 14, 15, 19, 15, 10, 18, 16, 19, 18, 13,
       11, 14, 18, 11, 17

In [49]:
mean = np.mean(population)
mean

14.522

In [50]:
std = np.std(population)
std

2.8276343469409193

In [53]:
median = np.median(population)
median

15.0

In [69]:
from statistics import mode
mode = mode(population)
mode

18

In [61]:
var = np.var(population)
var

7.995515999999999

Sample with size 20

In [70]:
sample1 = np.random.choice(population,20)

In [64]:
mean1 = sample1.mean()
mean1

15.05

In [81]:
median1 = np.median(sample1)
mode1 = mode(sample1)
var1 = np.var(sample1)
std1 = np.std(sample1)
print('Sample - ')
print('median - ', median1, ' mode - ', mode1, ' variance - ', var1, ' standard deviation - ', std1)

Sample - 
median -  13.0  mode -  10  variance -  8.61  standard deviation -  2.9342801502242417


In [80]:
mode(sample1)

10

Sample with size 50

In [73]:
sample3 = np.random.choice(population, 50)
sample3

array([12, 12, 18, 15, 10, 19, 10, 11, 16, 15, 14, 10, 12, 14, 10, 16, 13,
       13, 13, 16, 17, 17, 12, 17, 13, 17, 15, 15, 18, 15, 18, 11, 14, 17,
       13, 16, 19, 17, 18, 10, 18, 17, 16, 14, 17, 16, 10, 16, 16, 11])

In [75]:
mean3 = np.mean(sample3) #Population - 14.522
mean3

14.58

In [76]:
median3 = np.median(sample3) #Population - 15
median3

15.0

In [79]:
mode3 = mode(sample3)
mode3

16

As sample size increases, the values are closer to the population values